---
- hosts: webservers
  become: true
  tasks:
  - name: Install Java
    yum: 
      name= "{{ item }}"
      state=absent
    with_items:
      - 'java-1.8.0-openjdk'
      - 'java-1.8.0-openjdk-devel'
