---
- hosts: webservers
  become: true
  tasks:
  - name: Stop Tomcat
    service: name=tomcat state=stopped
  - name: Check that war file exist
    stat:
      path: /root/apache-tomcat-8.5.81/webapps/HelloWorldPramod.war
    register: stat_result

  - name: Delete the war file, if it exist already
    file:
      path: /root/apache-tomcat-8.5.81/webapps/HelloWorldPramod.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that GAMEOFLIFE dir exist
    stat:
      path: /usr/share/tomcat/webapps/gameoflife
    register: stat_result
  - name: Delete the GAMEOFLIFE dir, if it exist already
    file:
      path: /root/apache-tomcat-8.5.81/webapps/HelloWorldPramod
      state: absent
    when: stat_result.stat.exists == True
  - name: Deploy War File
    get_url:
       url: http://13.233.194.253:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife&p=war&v=LATEST
       dest: root/apache-tomcat-8.5.81/webapps/HelloWorldPramod.war
  - name: Start Tomcat
    service: name=tomcat state=started
